# Generated by Django 4.2.13 on 2024-05-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendpg', '0003_tracks_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
